from django.urls import path

from .views import (
    APIRootView,
    AppointmentCreateView,
    AppointmentDetailView,
    DoctorDetailView,
    DoctorListView,
    DocumentDownloadView,
    LoginView,
    MyAppointmentListView,
    PatientDocumentUploadView,
    PatientMedicalRecordView,
    PatientMeView,
    RefreshView,
    RegisterView,
    StaffAppointmentListView,
    StaffAppointmentUpdateView,
    StaffDocumentDeleteView,
    StaffEmailLogDetailView,
    StaffEmailLogListView,
    StaffMeView,
    StaffNoteVisibilityView,
    StaffPatientDocumentsView,
    StaffPatientNotesView,
    StaffPatientRecordView,
    StaffSendEmailView,
)
from .payment_views import (
    CreateCheckoutSessionView,
    stripe_webhook,
    verify_payment,
    payment_history,
    download_invoice,
)

urlpatterns = [
    path("", APIRootView.as_view(), name="api_root"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/refresh/", RefreshView.as_view(), name="token_refresh"),
    path("doctors/", DoctorListView.as_view(), name="doctor_list"),
    path("doctors/<int:pk>/", DoctorDetailView.as_view(), name="doctor_detail"),
    path("patients/me/", PatientMeView.as_view(), name="patient_me"),
    path("staff/me/", StaffMeView.as_view(), name="staff_me"),
    path("appointments/", AppointmentCreateView.as_view(), name="appointment_create"),
    path("appointments/my/", MyAppointmentListView.as_view(), name="appointment_list"),
    path("appointments/<int:pk>/", AppointmentDetailView.as_view(), name="appointment_detail"),
    path("staff/appointments/", StaffAppointmentListView.as_view(), name="staff_appointment_list"),
    path(
        "staff/appointments/<int:pk>/",
        StaffAppointmentUpdateView.as_view(),
        name="staff_appointment_update",
    ),
    path("staff/emails/", StaffEmailLogListView.as_view(), name="staff_email_log_list"),
    path("staff/emails/<int:pk>/", StaffEmailLogDetailView.as_view(), name="staff_email_log_detail"),
    path("staff/emails/send/", StaffSendEmailView.as_view(), name="staff_send_email"),
    # Medical Records - Patient endpoints
    path("records/me/", PatientMedicalRecordView.as_view(), name="patient_medical_record"),
    path("records/me/documents/", PatientDocumentUploadView.as_view(), name="patient_document_upload"),
    # Medical Records - Staff endpoints
    path("staff/patients/<int:patient_id>/record/", StaffPatientRecordView.as_view(), name="staff_patient_record"),
    path("staff/patients/<int:patient_id>/notes/", StaffPatientNotesView.as_view(), name="staff_patient_notes"),
    path("staff/patients/<int:patient_id>/documents/", StaffPatientDocumentsView.as_view(), name="staff_patient_documents"),
    path("staff/notes/<int:note_id>/", StaffNoteVisibilityView.as_view(), name="staff_note_visibility"),
    path("staff/documents/<int:document_id>/", StaffDocumentDeleteView.as_view(), name="staff_document_delete"),
    # Document download (secure, permission-checked)
    path("documents/<int:document_id>/download/", DocumentDownloadView.as_view(), name="document_download"),
    # Payment endpoints
    path("payments/checkout-session/", CreateCheckoutSessionView.as_view(), name="create_checkout_session"),
    path("payments/webhook/", stripe_webhook, name="stripe_webhook"),
    path("payments/verify/", verify_payment, name="verify_payment"),
    path("payments/my/", payment_history, name="payment_history"),
    path("payments/<int:payment_id>/invoice/", download_invoice, name="download_invoice"),
]
