import { useState } from 'react'
import { localDateTime } from '../utils/emr'
import { dashboardCounts, statusLabels } from '../utils/emrWorkspace'

const when = value => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'No due date'

export default function EMRDashboard({ data, userId, saving, onAdd, onUpdate, onPatient, onRefresh }) {
  const [date, setDate] = useState('')
  const [mine, setMine] = useState(false)
  const [patient, setPatient] = useState('')
  const [visitStatus, setVisitStatus] = useState('ACTIVE')
  const [taskStatus, setTaskStatus] = useState('OPEN')
  const counts = dashboardCounts(data.visits, data.tasks, userId)
  const match = item => (!mine || item.assigned_to === userId) && (!patient || String(item.patient) === patient)
  const visits = data.visits.filter(visit => match(visit) && (!date || localDateTime(visit.scheduled_start).slice(0, 10) === date) && (visitStatus === 'ALL' || (visitStatus === 'ACTIVE' ? ['SCHEDULED', 'IN_PROGRESS'].includes(visit.status) : visit.status === visitStatus)))
  const tasks = data.tasks.filter(task => match(task) && (!date || (task.due_at && localDateTime(task.due_at).slice(0, 10) === date)) && (taskStatus === 'ALL' || task.status === taskStatus)).sort((a, b) => (a.status === 'DONE') - (b.status === 'DONE') || (b.priority === 'HIGH') - (a.priority === 'HIGH') || (a.due_at ? new Date(a.due_at).getTime() : Infinity) - (b.due_at ? new Date(b.due_at).getTime() : Infinity) || a.id - b.id)
  const chartButton = item => <button className="btn btn-link emr-chart-link p-0 text-start" type="button" disabled={saving} onClick={() => onPatient(item.patient)}>{item.patient_name}</button>
  const badge = status => <span className={`badge ${['COMPLETED', 'DONE'].includes(status) ? 'text-bg-success' : status === 'IN_PROGRESS' ? 'text-bg-primary' : 'text-bg-secondary'}`}>{statusLabels[status]}</span>
  return <section aria-label="Visit and task dashboard">
    <div className="d-flex flex-wrap justify-content-between gap-2 align-items-center mb-3"><h2 className="h4 mb-0">Visits & tasks</h2><div className="d-flex flex-wrap gap-2"><button className="btn btn-outline-secondary btn-sm" type="button" disabled={saving} onClick={onRefresh}>Refresh</button><button className="btn btn-outline-primary btn-sm" type="button" disabled={saving} onClick={() => onAdd('visit')}>Schedule visit</button><button className="btn btn-primary btn-sm" type="button" disabled={saving} onClick={() => onAdd('task')}>Add task</button></div></div>
    <div className="row g-3 mb-4">{[["Today's visits", counts.today], ['Open tasks', counts.open], ['Overdue tasks', counts.overdue], ['My open tasks', counts.mine]].map(([label, value]) => <div className="col-6 col-lg-3" key={label}><div className="card emr-metric"><div className="card-body"><span className="text-muted small">{label}</span><strong className="d-block h2 mb-0 mt-1">{value}</strong></div></div></div>)}</div>
    <div className="card mb-4"><div className="card-body"><div className="row g-3 align-items-end"><div className="col-md-4"><label className="form-label small" htmlFor="emr-work-patient">Patient</label><select className="form-select" id="emr-work-patient" value={patient} onChange={event => setPatient(event.target.value)}><option value="">All patients</option>{data.patients.map(person => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select></div><div className="col-md-4"><label className="form-label small" htmlFor="emr-work-date">Visit or due date</label><input className="form-control" id="emr-work-date" type="date" value={date} onChange={event => setDate(event.target.value)} /></div><div className="col-md-4"><div className="form-check mb-2"><input className="form-check-input" id="emr-work-mine" type="checkbox" checked={mine} onChange={event => setMine(event.target.checked)} /><label className="form-check-label" htmlFor="emr-work-mine">Assigned to me</label></div><button className="btn btn-link btn-sm p-0" type="button" onClick={() => { setDate(''); setPatient(''); setMine(false); setVisitStatus('ACTIVE'); setTaskStatus('OPEN') }}>Reset filters</button></div></div></div></div>
    <div className="row g-4"><div className="col-xl-6"><div className="card h-100"><div className="card-body"><div className="emr-filter-heading mb-3"><h3 className="h5 mb-0">Visits ({visits.length})</h3><div className="emr-filter-control"><label className="form-label" htmlFor="emr-visit-status">Visit status</label><select className="form-select form-select-sm emr-status-filter" id="emr-visit-status" value={visitStatus} onChange={event => setVisitStatus(event.target.value)}><option value="ACTIVE">Upcoming & in progress</option><option value="ALL">All visits</option>{['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'].map(status => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></div></div>
      {!visits.length && <p className="text-muted mb-0">No visits match these filters.</p>}{visits.map(visit => <article className="emr-work-item" key={visit.id}><div className="d-flex flex-wrap gap-2 justify-content-between align-items-start"><div><h4 className="h6 mb-1">{visit.purpose}</h4>{chartButton(visit)}</div>{badge(visit.status)}</div><p className="small text-muted mt-2 mb-2">{when(visit.scheduled_start)} · {visit.assigned_name || 'Unassigned'} · Visit #{visit.id}</p><div className="d-flex flex-wrap gap-2">{visit.status === 'SCHEDULED' && <button className="btn btn-outline-primary btn-sm" disabled={saving} onClick={() => onUpdate('visits', visit, 'IN_PROGRESS')}>Start visit</button>}{visit.status === 'IN_PROGRESS' && <button className="btn btn-primary btn-sm" disabled={saving} onClick={() => onUpdate('visits', visit, 'COMPLETED')}>Complete visit</button>}{['SCHEDULED', 'IN_PROGRESS'].includes(visit.status) ? <button className="btn btn-outline-secondary btn-sm" disabled={saving} onClick={() => onUpdate('visits', visit, 'CANCELLED')}>Cancel visit</button> : <button className="btn btn-outline-primary btn-sm" disabled={saving} onClick={() => onUpdate('visits', visit, visit.status === 'COMPLETED' ? 'IN_PROGRESS' : 'SCHEDULED')}>Reopen visit</button>}</div>{visit.updated_by_name && <p className="small text-muted mt-2 mb-0">Updated by {visit.updated_by_name}</p>}</article>)}
    </div></div></div><div className="col-xl-6"><div className="card h-100"><div className="card-body"><div className="emr-filter-heading mb-3"><h3 className="h5 mb-0">Tasks ({tasks.length})</h3><div className="emr-filter-control"><label className="form-label" htmlFor="emr-task-status">Task status</label><select className="form-select form-select-sm emr-status-filter" id="emr-task-status" value={taskStatus} onChange={event => setTaskStatus(event.target.value)}><option value="OPEN">Open tasks</option><option value="DONE">Completed tasks</option><option value="ALL">All tasks</option></select></div></div>
      {!tasks.length && <p className="text-muted mb-0">No tasks match these filters.</p>}{tasks.map(task => <article className="emr-work-item" key={task.id}><div className="d-flex flex-wrap justify-content-between gap-2 align-items-start"><div><h4 className="h6 mb-1">{task.title}</h4>{chartButton(task)}</div><div className="d-flex gap-1">{task.priority === 'HIGH' && <span className="badge text-bg-warning">High priority</span>}{badge(task.status)}</div></div>{task.details && <p className="small emr-note-text mt-2 mb-2">{task.details}</p>}<p className="small text-muted mt-2 mb-2">{when(task.due_at)} · {task.assigned_name || 'Unassigned'}{task.visit ? ` · Visit #${task.visit}` : ''}{task.status === 'OPEN' && task.due_at && new Date(task.due_at) < new Date() && <span className="badge text-bg-warning ms-2">Overdue</span>}</p><button className="btn btn-outline-primary btn-sm" disabled={saving} onClick={() => onUpdate('tasks', task, task.status === 'OPEN' ? 'DONE' : 'OPEN')}>{task.status === 'OPEN' ? 'Complete task' : 'Reopen task'}</button>{task.completed_at && <p className="small text-muted mt-2 mb-0">Completed {when(task.completed_at)} by {task.completed_by_name}</p>}</article>)}
    </div></div></div></div>
  </section>
}
