# Generated by Django 5.0.6 on 2026-01-03 05:02

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.utils import timezone


def seed_users_profiles_and_appointments(apps, schema_editor):
    User = apps.get_model("core", "User")
    PatientProfile = apps.get_model("core", "PatientProfile")
    Appointment = apps.get_model("core", "Appointment")

    patient, _ = User.objects.get_or_create(
        email="patient@example.com",
        defaults={
            "role": "PATIENT",
            "first_name": "Pat",
            "last_name": "Smith",
            "is_active": True,
        },
    )
    if not patient.password:
        patient.password = make_password("Pass1234!")
        patient.save(update_fields=["password"])

    staff, _ = User.objects.get_or_create(
        email="staff@example.com",
        defaults={
            "role": "STAFF",
            "first_name": "Sam",
            "last_name": "Taylor",
            "is_staff": True,
            "is_active": True,
        },
    )
    if not staff.password:
        staff.password = make_password("StaffPass123!")
        staff.save(update_fields=["password"])

    PatientProfile.objects.get_or_create(
        user=patient,
        defaults={
            "date_of_birth": "1990-06-15",
            "phone_number": "+1-555-0100",
            "address": "123 Demo Street, Springfield",
            "emergency_contact_name": "Alex Smith",
            "emergency_contact_phone": "+1-555-0101",
            "insurance_provider": "Demo Health",
            "insurance_policy_number": "DHE-123456",
        },
    )

    now = timezone.now()
    Appointment.objects.update_or_create(
        patient=patient,
        reason="Annual physical",
        defaults={
            "requested_start": now + timezone.timedelta(days=2),
            "scheduled_start": now + timezone.timedelta(days=3),
            "status": "CONFIRMED",
            "patient_notes": "General checkup request.",
            "staff_notes": "Scheduled for morning slot.",
        },
    )
    Appointment.objects.update_or_create(
        patient=patient,
        reason="Follow-up consultation",
        defaults={
            "requested_start": now + timezone.timedelta(days=7),
            "scheduled_start": None,
            "status": "REQUESTED",
            "patient_notes": "Discuss lab results.",
            "staff_notes": "",
        },
    )


def remove_seed_data(apps, schema_editor):
    User = apps.get_model("core", "User")
    PatientProfile = apps.get_model("core", "PatientProfile")
    Appointment = apps.get_model("core", "Appointment")

    Appointment.objects.filter(patient__email="patient@example.com").delete()
    PatientProfile.objects.filter(user__email="patient@example.com").delete()
    User.objects.filter(email__in=["patient@example.com", "staff@example.com"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_patientprofile'),
    ]

    operations = [
        migrations.RunPython(seed_users_profiles_and_appointments, remove_seed_data),
    ]
