# Generated by Django 5.0.6 on 2026-01-03 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WELCOME', 'Welcome'), ('APPT_REQUESTED', 'Appointment Requested'), ('APPT_CONFIRMED', 'Appointment Confirmed'), ('APPT_COMPLETED', 'Appointment Completed'), ('APPT_CANCELED', 'Appointment Canceled'), ('STAFF_CUSTOM', 'Staff Custom Email')], max_length=20)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_emails', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.appointment')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='core_notifi_created_1305e6_idx'), models.Index(fields=['event_type'], name='core_notifi_event_t_637c4a_idx'), models.Index(fields=['status'], name='core_notifi_status_33f2d8_idx')],
            },
        ),
    ]
