# Generated by Django 5.0.6 on 2026-01-03 17:55

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_text', models.TextField(blank=True, help_text='Medical history summary')),
                ('allergies_text', models.TextField(blank=True, help_text='Known allergies')),
                ('medications_text', models.TextField(blank=True, help_text='Current medications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='core.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('VISIT', 'Visit Note'), ('LAB', 'Lab Result'), ('PRESCRIPTION', 'Prescription'), ('GENERAL', 'General Note')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('STAFF_ONLY', 'Staff Only'), ('SHARED_WITH_PATIENT', 'Shared with Patient')], default='STAFF_ONLY', max_length=30)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_notes', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.medicalrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LAB_RESULT', 'Lab Result'), ('PRESCRIPTION', 'Prescription'), ('IMAGING', 'Imaging'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('visibility', models.CharField(choices=[('PATIENT_AND_STAFF', 'Patient and Staff'), ('STAFF_ONLY', 'Staff Only')], default='PATIENT_AND_STAFF', max_length=30)),
                ('file', models.FileField(upload_to=core.models.medical_document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.medicalrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
