# Generated by Django 6.0 on 2026-03-05 02:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_default_patient_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.models.career_resume_upload_path),
        ),
    ]
