# Generated by Django 6.0 on 2026-10-01 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_jobapplication_sensitive_data_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEMRPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('primary_condition', models.CharField(max_length=200)),
                ('allergies', models.JSONField(default=list)),
                ('medications', models.JSONField(default=list)),
                ('care_plan', models.JSONField(default=list)),
                ('history', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='DemoEMRNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('visit_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.TextField(blank=True, max_length=5000)),
                ('interventions', models.TextField(blank=True, max_length=5000)),
                ('response', models.TextField(blank=True, max_length=5000)),
                ('plan', models.TextField(blank=True, max_length=5000)),
                ('vitals', models.JSONField(default=dict)),
                ('completed_tasks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized')], default='DRAFT', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('finalized_by_name', models.CharField(blank=True, max_length=200)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='core.demoemrnote')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_emr_notes', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_demo_emr_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='core.demoemrpatient')),
            ],
            options={
                'ordering': ('-visit_at', '-created_at'),
            },
        ),
    ]
