# Generated by Django 6.0 on 2026-10-01 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_demoemrpatient_demoemrnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoemrnote',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
